server:
  port: 8762 #启动端口
logging:
  level:
    com.github.hollykunge.security.admin: DEBUG

spring:
  application:
    name: springboot-rabbitmq
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    #需要修改地址
    host: ${RABBIT_MQ_HOST:10.11.24.123}
    port:  ${RABBIT_MQ_PORT:5672}
    username: fansq
    password: 123456789
    virtual-host: /
    ###使用rabbitmq消息发送确认机制
    publisher-confirms: true
    listener:
      simple:
        #开启手动ack
        acknowledge-mode: manual
        retry:
          #重试机制适用于门户服务数据库暂时24秒内连接不上等情况
          enabled: true
          #最大重试次数
          max-attempts: 3
          #重试间隔次数
          initial-interval: 3000ms